stages:
  get_features_n_split:
    cmd: python3 scripts/data_preprocessing/get_features_n_split.py data/raw/wines_SPA.csv
    deps:
    - data/raw/wines_SPA.csv
    - scripts/data_preprocessing/get_features_n_split.py
    params:
    - split.split_ratio
    outs:
    - data/stage_1
  preprocessing:
    cmd: python3 scripts/data_preprocessing/preprocessing.py data/stage_1/X_Train.csv data/stage_1/y_Train.csv data/stage_1/X_test.csv data/stage_1/y_test.csv
    deps:
    - data/stage_1/X_Train.csv
    - data/stage_1/y_Train.csv
    - data/stage_1/X_test.csv
    - data/stage_1/y_test.csv
    - scripts/data_preprocessing/preprocessing.py
    outs:
    - data/stage_2
  train:
    cmd: python3 scripts/model_learning/svr.py data/stage_2/X_Train.csv data/stage_2/y_Train.csv
    deps:
    - data/stage_2/X_Train.csv
    - data/stage_2/y_Train.csv
    - scripts/model_learning/svr.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python3 scripts/model_learning/eval.py data/stage_2/X_test.csv data/stage_2/y_test.csv models/model.pkl
    deps:
    - data/stage_2/X_test.csv
    - data/stage_2/y_test.csv
    - models/model.pkl
    - scripts/model_learning/eval.py
    metrics:
    - evaluate/r2score.json:
        cache: false